version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        time_zone 'Asia/Tehran'
        smtp_enable true
        smtp_address "mail.example.com"
        smtp_port 587
        smtp_user_name "user@example.com"
        smtp_password "YOUR_PASSWORD_HERE"
        smtp_domain "mail.example.com"
        smtp_authentication "plain"
        smtp_enable_starttls_auto true
    ports:
      - '22080:80'
      - '22443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
